import Image from "next/image";

type ShepherdProps = {
  className?: string;
  priority?: boolean;
  sizes?: string;
  /** Flip horizontally so the dog leaps to the left */
  flip?: boolean;
};

/**
 * Solid brass silhouette derived from the original Carolo Canis wordmark
 * (idnthumb.jpeg). Generated by `scripts/extract_shepherd.py`.
 */
export function Shepherd({
  className = "",
  priority = false,
  sizes = "(min-width: 1024px) 640px, 90vw",
  flip = false,
}: ShepherdProps) {
  return (
    <Image
      src="/shepherd-leap.png"
      alt=""
      fill
      priority={priority}
      sizes={sizes}
      className={`object-contain ${flip ? "-scale-x-100" : ""} ${className}`}
    />
  );
}
